export const Requirements = [
  "Sitout",
  "Formal Living Area",
  "Kids Bedrooms",
  "Dining Room",
  "Courtyard",
  "Store Room",
  "Game Room",
  "Theatre Room",
  "varanda",
  "Home Office",
  "Library",
  "Laundry Room",
  "Conservatory",
  "Study Room",
  "Deck",
  "Servant Room",
  "Stair",
  "Elevator",
  "Swimming Pool",
  "Landscaping",
  "Basement",
  "Garage",
  "WaterBody",
  "Porch",
  "Patio",
];
